version: 2.1

jobs:
  build-frontend:
    docker:
      - image: cimg/node:16.5.0
    steps:
      - checkout
      - restore_cache:
          keys: ['frontend-build-{{ checksum "frontend/package.json" }}']
      - run:
          name: Build front-end
          command: |
            cd frontend
            npm install
            npm run build
      - save_cache:
          paths: [frontend/node_modules]
          key: frontend-build-{{ checksum "frontend/package.json" }}

  build-backend:
    docker:
      - image: cimg/node:16.5.0
    steps:
      - checkout
      - restore_cache:
          keys: ['backend-build-{{ checksum "backend/package.json" }}']
      - run:
          name: Back-end build
          command: |
            cd backend
            npm install
      - save_cache:
          paths: [backend/node_modules]
          key: backend-build-{{ checksum "backend/package.json" }}

  test-frontend:
    docker:
      - image: cimg/node:16.5.0
    steps:
      - checkout
      - restore_cache:
          keys: ['frontend-build-{{ checksum "frontend/package.json" }}']
      - run:
          name: Test the code
          command: |
            cd frontend
            npm run test             

  test-backend:
    docker:
      - image: cimg/node:16.5.0
    steps:
      - checkout
      - restore_cache:
          keys: ['backend-build-{{ checksum "backend/package.json" }}']
      - run:
          name: Test the code
          command: |
            cd backend
            npm run test      

workflows:
  default:
    jobs:
      - build-frontend
      - build-backend
      - test-frontend:
          requires: [build-frontend]
      - test-backend:
          requires: [build-backend]
